# Reference: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true

MD033: false
MD034: false

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013: false
